### PR TITLE
[ADD][9.0] travis: Add travis for v9

### PR DESCRIPTION
**Pull request by lasley**
This PR adds travis file for v9

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Maybe you can add also Transifex support

**Comment by lasley** [comment]
@pedrobaeza I was in the process of making an issue for this - I can't find the credentials in https://github.com/OCA/maintainer-quality-tools/issues/194

If this is something you can take care of (or better, guide me to/on), I can add immediately 😄

**Comment by pedrobaeza** [comment]
As a new repository, the secure is not created there, so we need to manually get it with gem instructions. Can you try it?

**Comment by lasley** [comment]
The instructions say `your-password`. To confirm, I just make something random here?

**Comment by lasley** [comment]
Seems to have worked. I'll submit that commit to 8.0 as well

**Comment by pedrobaeza** [comment]
Uhm, we need to provide the OCA password, so it's not possible you to do it. Let me do it for you.

**Comment by lasley** [comment]
Oh so it didn't work? False 🍏  😢

**Comment by pedrobaeza** [comment]
Uhm, I'm not sure if it's a false positive... Try with an invalid secure to see

**Comment by lasley** [comment]
Seems it is. Wonder if this is caused by OCA/maintainer-quality-tools#340 - @moylop260 any thoughts?

**Comment by lasley** [comment]
@pedrobaeza - I'm going to revert Transifex changes on this. Did you want to submit a PR to this branch with them, submit a new PR to the repo, or just drop the secret here and have me handle it?

**Comment by moylop260** [comment]
👍 
The transifex error is not related with https://github.com/OCA/maintainer-quality-tools/pull/340
We need the new secure password from @pedrobaeza 
IMHO we can work it in other PR

**Comment by pedrobaeza** [comment]
This is the correct secure:

```
secure: "P8zdckjpfLcTbz/kq8FNOgVMHjFNESk0H5/lHQQinBg7nr3oiWIg1tStroOJQtIn26+qWT2GZUX8V90FNCH6aGvqH8oIGguhZGibFHINarho2LjQd5DhhyIgm0qF12H31hFLOQokmlyx9r3A8Sw6EWPtWQ/vFBsL97ErhMK7AyX9vhDZCvpLX/zQyGpSXGNbogpmlhrV4z1RBBE9AtvPienTqkdz86a5wFOSjXM8Is5QVWZfKyFIxytiIxDERt+AS71FNXdrh73qRNbMIkULO+ROcdgGcMXdigiSZmny3n/kkty3I7lZO6K6bXLPugfii4Y2EiyJm+Mod99p9AAPAdifKbXF+ZJDWqkVbeooCBt93V1juQwsn1RT1Yms3U6F2lrw9oMm1M27ht+DSfcKMhBdtvDMN4tzU1zwxUx9kZ+oPmSDqSvPECIlUpHOvn4IUBEEuO1fHzooSX9scMFKJAx4Q7wsuPyUySFUy0J22AlbJcKcZOqtVw3++9WH1foxSWxMHjL/UjLSAn1B03xJAj3hALHMj61+R1HA/9v1/UCigwxkpbsMrWJK6SkXqBUcd5ECiHEScwNXr0nKLEydZOqorofPk4BjroGGyTd2h1iqa1suZ2zb3QJXcPvlsxzO/hvLm+wdzMyeJTe4I78kOkfGlmzSWJgoEq2ngad1rng="
```

**Comment by lasley** [comment]
Thanks @pedrobaeza - secure updated

**Comment by pedrobaeza** [comment]
Merging then!

**Pull request merged**
